baseURL = 'https://dcashpeterson.github.io/'
defaultContentLanguage = "en"
title = 'When Pigs Fly'
theme = 'itheme'

[params]
[[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/dcashpeterson'
[[params.socialMedia]]
    name = 'BlueSky'
    url = 'bsky.app/profile/derekcp.com'
